version: '2'
services:
  backend:
    build: ./tutorium/backend
    container_name: backend
    volumes:
     - ./tutorium/backend/src:/app/src
    command: npm start
    ports:
     - "8123:8123"
    links:
     - database:database
    depends_on:
     - database
    environment:
     - DATABASE_HOST=database
  database:
    build: ./tutorium/database
    volumes:
     - ./tutorium/database/setup:/docker-entrypoint-initdb.d # run setup.sql on init
    ports:
     - "3306:3306"
