version: '2'
services:
  front-end:
    build: ./tutorium/front-end
    container_name: front-end
    volumes:
     - ./tutorium/front-end/src:/app/src
     - ./tutorium/front-end/public:/app/public
    command: npm start
    ports:
     - "3000:3000"
    links: 
     - back-end:back-end
    depends_on:
     - back-end
  back-end:
    build: ./tutorium/back-end
    container_name: back-end
    volumes:
     - ./tutorium/back-end/src:/app/src
    command: npm start
    ports:
     - "8123:8123"
    links:
     - database:database
    depends_on:
     - database
    environment:
     - DATABASE_HOST=database
  database:
    build: ./tutorium/database
    volumes:
     - ./tutorium/database/setup:/docker-entrypoint-initdb.d
    ports:
     - "3306:3306"
