FROM mysql:5

ENV MYSQL_ROOT_PASSWORD 123
ENV MYSQL_DATABASE tutorium
ENV MYSQL_USER tutorium
ENV MYSQL_PASSWORD 123

# RUN mkdir docker-entrypoint-initdb.d
# ADD setup.sql /docker-entrypoint-initdb.d

EXPOSE 3306